name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    name: Prebuild Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
    timeout-minutes: 30
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --arch ${{ matrix.arch }} -r electron -t 33.2.0
